stages:
  - build
  - test

variables:
  JDK_VERSION : "8"
  GIT_SSL_NO_VERIFY: "1"

.build-template: &build-template
  stage: build
  only:
    - dev
  image: git.stable.innovation.insee.eu:50000/innovation/images-ci/jdk:$JDK_VERSION
  script:
    - cd $MODULE_NAME
    - mvn build

.test-template: &test-template
  stage: test
  only:
    - dev
  image: git.stable.innovation.insee.eu:50000/innovation/images-ci/jdk:$JDK_VERSION
  script:
    - cd $MODULE_NAME
    - mvn clean test
