stages:
  - test

variables:
  JDK_VERSION : "8"
  GIT_SSL_NO_VERIFY: "1"

main-module-test:
  stage: test
  image: git.stable.innovation.insee.eu:50000/innovation/images-ci/jdk:$JDK_VERSION
  script:
    - cd french-lemmatiser
    - mvn install
    - cd ../tokensregex-builder
    - mvn install
    - cd ../insee-ner-tagger
    - mvn install
