stages:
  - build
  - test

variables:
  JDK_VERSION : "8"
  GIT_SSL_NO_VERIFY: "1"

.build-template: &build-template
  stage: build
  image: git.stable.innovation.insee.eu:50000/innovation/images-ci/jdk:$JDK_VERSION
  script:
    - cd $MODULE_NAME
    - mvn clean install

lemmatiser:
  <<: *build-template
  variables:
    MODULE_NAME: "french-lemmatiser"

tokensregex-builder:
  <<: *build-template
  variables:
    MODULE_NAME: "tokensregex-builder"

#insee-ner-tagger:
#  stage: test
#  image: git.stable.innovation.insee.eu:50000/innovation/images-ci/jdk:$JDK_VERSION
#  script: